### ISSUE TITLE
gmail supported?

### ISSUE THREAD

**Issue by frap** [logstash-plugins/logstash-input-imap#13]
I for the life of me cant get gmail to work. I can login via commandline via openssl so gmail is setup correctly. get the following errors.
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::IMAP host=>"imap.google.com", user=>"ateaalerts@ateasystems.com", content_type=>"text/plain", check_interval=>600, password=><password>, secure=>true, port=>993, fetch_count=>15, tags=>["mail"], codec=><LogStash::Codecs::Plain charset=>"UTF-8">, verify_cert=>true, folder=>"INBOX", lowercase_headers=>true, delete=>false>
  Error: initialize: name or service not known
  Exception: SocketError
  Stack: org/jruby/ext/socket/RubyTCPSocket.java:129:in `initialize'
org/jruby/RubyIO.java:1179:in `open'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/imap.rb:1034:in `initialize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-imap-2.0.2/lib/logstash/inputs/imap.rb:60:in `connect'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-imap-2.0.2/lib/logstash/inputs/imap.rb:75:in `check_mail'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-imap-2.0.2/lib/logstash/inputs/imap.rb:68:in `run'
org/jruby/RubyProc.java:281:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:20:in `interval'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-imap-2.0.2/lib/logstash/inputs/imap.rb:67:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:206:in `inputworker'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:199:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"218", :method=>"inputworker"}

**Comment by wiibaa** [comment]
Hum...sorry for the silly remark but are you using **imap.google.com** as the server name ??
That would explain the error **Error: initialize: name or service not known** because this hostname does not exists... Did you try with **imap.gmail.com**

**Comment by frap** [comment]
Duh Im an egit :) - sorry! I'm obviously getting too old or selective dyslexia - my openssl commands used right url and worked - funnily! Man I feel like a complete moron..

Thanks for helping me out

**Comment by bardie** [comment]
imap.googlemail.com works for me

https://www.programcreek.com/python/example/2875/imaplib.IMAP4_SSL
