### ISSUE TITLE
Logstash cannot fetch attachment of email by using IMAP plugin

### ISSUE THREAD

**Issue by xuanhai266** [logstash-plugins/logstash-input-imap#27]
Dear all,

I try to use Logstash IMAP plugin to fetch email from a mail server and store to Elasticsearch.
However, Logstash IMAP plugin cannot fetch **attachment** of email.
Could you please help me to check again?
Thank you.

- Version: 5.5.1
- Operating System: CentOS 7.3
- Config File:
```
input{
        imap {
                type => mail
                host => "mail_server_ip"
                user => "my_user_name"
                password => "my_pass_word"
                port => 143
                secure => "false"
                check_interval => 1
                strip_attachments => "false"
                content_type => "multipart/mixed"
        }
}
```
- Sample Data: an email with attachment
- Steps to Reproduce:
1. Start logstash by command: /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/
2. Check Kibana

**Comment by jordansissel** [comment]
I'm confused, can you help me understand your problem further?

I see this:

>                 strip_attachments => "true"

This tells the plugin to strip attachments, right? So you won't get any attachments in your Logstash imap input because of your configuration.

**Comment by xuanhai266** [comment]
I tried to set:
strip_attachments => "false"
but it still does not fetch attachment of email.

**Comment by xuanhai266** [comment]
I create directory: /etc/elasticsearch/attachments.
And now I can get attachment of email by using Logstash IMAP plugin.

**Comment by livelace** [comment]
@xuanhai266 

https://github.com/logstash-plugins/logstash-input-imap/blob/bc085100be613ab9e19191ea9146ccaf17ea47a2/lib/logstash/inputs/imap.rb#L33

You should set your custom mime type for a right proccessing.

**Comment by xuanhai266** [comment]
I
