### ISSUE TITLE
Attachment Saving - Feature Request

### ISSUE THREAD

**Issue by nicpenning** [logstash-plugins/logstash-input-imap#29]
If I am not mistaken, you can not save attachment information from files such as .xlsx, .doc, .zip and others without causing the plugin to break ( Error: Can not decode an entire message, try calling #decoded on the various fields and body or parts if it is a multipart message.) (https://github.com/logstash-plugins/logstash-input-imap/issues/25). Unless it is a text file. If it is a text file then it appears to store that data in Message.

What would be helpful is the management of the attachments inside of the email. The idea is to identify attachments and having the capability to output to X (Two examples, a file location, or base64 encoded string in ES).

If this already does this, then I will have to report a bug. 

Server Ubuntu LTS 16.04

ES - 6.2.1
Kibana - 6.2.1
LogStash - 6.2.1

Email source: Outlook/Hotmail Account
Input Email (IMAP): Gmail account

![image](https://user-images.githubusercontent.com/5582679/36395771-715c7bbe-1580-11e8-9d09-dbc442ea0706.png)

Let me know if there is anything else I can contribute.

Thanks in advance.

Nic

**Comment by nicpenning** [comment]
After diving further into this, it should be possible.

From a config standpoint, it would be great to have the option:
config :store_attachments, :validate => :boolean, :default => false
config :attachment_storage_path, :validate => :string, :default => "public/attachments/"
Note* public/attachments/ is hard coded in this config write now, would have to make this a variable.

It would be useful then to store the file names/paths into a variable that could then be used for output.

Below is code that should allow this functionality to take place.

(Credit for a majority of the code: http://burnignorance.com/ruby-development-tips/downloading-attachments-from-mails-through-imap-in-rails/ by Shatabdi Mohapatra , Ruby on Rails Developer, Mindfire Solutions.)

require 'net/imap'
require 'mail'
require 'active_support'
require 'active_support/core_ext'

imap = Net::IMAP.new('imap.gmail.com', 993, true)
imap.login('username@gmail.com', 'pa5sword')
imap.select('INBOX')
imap.search('UNSEEN').each do |message_id|
  body = imap.fetch(message_id, 'RFC822')[0].attr['RFC822']
  mail = Mail.new(body)

fileNames = Array.new
  unless mail.attachments.blank?
    unless File.exists?("public/attachments/#{mail.message_id}")
      Dir.mkdir(File.join("public/attachments", "#{mail.message_id}"), 0700)
    end
    mail.attachments.each do |attachment|
       File.open("public/attachments/#{mail.message_id}/#{attachment.filename}", 'wb') do |file|
       file.write(attachment.body.decoded)
       #Store file names and their destination path in this array called fileNames
       fileNames.push "public/attachments/#{mail.message_id}/#{attachment.filename}"
       end
    end
  end
  imap.logout
  imap.disconnect

#Print out all of the files and their locations here. This would be perfect for storing into ES instead of the whole binary.
fileNames.each do |fileNames|
   puts fileNames
end
end

**Comment by nicpenning** [comment]
Hi, @ilongley!

Are you looking to fix the error message or ingest attachments?

The code above was working to store the attachment from an email to a local destination such as public/attachments by using the message id and attachment filename as shown above.

So for example if the imap reads your inbox and has 1 attachment called myfile.doc, then the imap plugin will store this file to public/attachments/uniquemessageid/myfile.doc

The last part prints out the attachments and where they are located.

**Comment by nicpenning** [comment]
Note: I modified the imap.rb plugin here (which could be different for your environment: ./logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.5/lib/logstash/inputs/imap.rb

**Comment by ilongley** [comment]
@nicpenning Perfect, thank you!

**Comment by pemontto** [comment]
@ilongley @nicpenning PR #48 solves this issue and works nicely with the ES attachment plugin for multiple attachments.

**Comment by karenzone** [comment]
Hi @nicpenning and @ilongley. @pemontto 's PR #48 has been approved and merged.  Thanks!

**Comment by ilongley** [comment]
@karenzone Works for me, thank you.

**Comment by karenzone** [comment]
Awesome! I'm closing this issue with much appreciation to you all. Thanks!
